# Generated by Django 3.2.4 on 2021-06-16 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='usuario',
            fields=[
                ('NomCompleto', models.CharField(max_length=30, verbose_name='Nombre del Usuario')),
                ('email', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='Correo del usuario')),
                ('direccion', models.CharField(max_length=40, verbose_name='Dirección del usuario')),
                ('contraseña', models.CharField(max_length=10, verbose_name='Contraseña del usuario')),
            ],
        ),
    ]
