# Generated by Django 3.2.4 on 2021-06-20 01:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_persona'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Persona',
        ),
    ]
